global_frame: map
track_unknown_space: true

footprint_padding: 0.01

width: 80
height: 80
origin_x: -40
origin_y: -40

static_map: true
rolling_window: false

# resolution: 0.1 # 0.05

# cost_scaling_factor: 1

static_layer:
  map_topic: map
  subscribe_to_updates: true
  lethal_cost_threshold: 51
  unknown_cost_value: -1


inflation:
  inflation_radius: 0.2
  cost_scaling_factor: 1
  inflate_unknown: true

obstacles_laser:
  obstacle_range: 7.5
  raytrace_range: 8

voxel_layer:
  observation_sources: octomap_voxel_grid
  octomap_voxel_grid: {
    topic: /octomap_point_cloud_centers,
    data_type: PointCloud2,
    clearing: true, 
    marking: true, 
    inf_is_valid: true,
    max_obstacle_height: 0.5,
    min_obstacle_height: -0.1 #test
  }

plugins:
  - {name: static_layer,              type: "costmap_2d::StaticLayer"}
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: voxel_layer,               type: "costmap_2d::VoxelLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}