#this should goes to /move_base/ namespace

controller_frequency: 10.0
planner_frequency: 0.5             # If the frequency is set to 0.0, the global planner will only run when a new goal is
                                  # received or the local planner reports that its path is blocked.
recovery_behaviour_enabled: true  # true
# controller_patience: 3
# oscillation_timeout: 3.0
# max_planning_retries: 3

recovery_behaviors: [
  {
    name: conservative_reset, 
    type: clear_costmap_recovery/ClearCostmapRecovery
  },
# {name: rotate_recovery, type: rotate_recovery/RotateRecovery},
  {
    name: aggressive_reset, 
    type: clear_costmap_recovery/ClearCostmapRecovery
  }
]

conservative_reset:
  reset_distance: 3

aggressive_reset:
  reset_distance: 0

# NavfnROS:
GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.1
  # publish_potential: true

TebLocalPlannerROS:
  odom_topic: /controller/odom
  map_frame: /map

  # Trajectory

  teb_autosize: True
  dt_ref: 0.1
  dt_hysteresis: 0.01
  global_plan_overwrite_orientation: True
  allow_init_with_backwards_motion: False
  max_global_plan_lookahead_dist: 3.0
  feasibility_check_no_poses: 5
  force_reinit_new_goal_dist: 2
  force_reinit_new_goal_angular: 1.5

  # Robot
  max_vel_x: 0.35
  max_vel_x_backwards: 0.35
  max_vel_theta: 3.0
  acc_lim_x: 0.1
  acc_lim_theta: 40
  min_turning_radius: 0.9
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "polygon"

    # radius: 0.2 # for type "circular"
    # line_start: [-0.1, 0.0] # for type "line"
    # line_end: [0.1, 0.0] # for type "line"
    # front_offset: 0.2 # for type "two_circles"
    # front_radius: 0.2 # for type "two_circles"
    # rear_offset: 0.2 # for type "two_circles"
    # rear_radius: 0.2 # for type "two_circles"
    vertices: [ [0.2, 0.1], [-0.2, 0.1], [-0.2, -0.1], [0.2, -0.1], [0.2, 0.1] ] # for type "polygon"

  wheelbase: 0.26

  # GoalTolerance
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  free_goal_vel: False

  # Obstacles
  min_obstacle_dist: 0.22
  inflation_dist: 0.3
  dynamic_obstacle_inflation_dist: 0.3
  include_dynamic_obstacles: True
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30
#  costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
  costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
  #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSMCCH"
  #costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull"
#  costmap_converter_plugin: "" # deactivate plugin
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5

  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.08
  weight_max_vel_x: 1
  weight_max_vel_y: 0
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_y: 0
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 5
  weight_kinematics_turning_radius: 10
  weight_optimaltime: 50     # select more faster paths
  weight_shortest_path: 0
  weight_obstacle: 50
  weight_dynamic_obstacle: 10 # not in use yet
  selection_alternative_time_cost: False

  # Homotopy Class Planner

  enable_homotopy_class_planning: True
  enable_multithreading: True
  simple_exploration: False
  max_number_classes: 4
  # roadmap_graph_no_samples: 15
  roadmap_graph_no_samples: 10
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False




    ## Configure plugins (namespace move_base/TebLocalPlannerROS/PLUGINNAME)
    ## The parameters must be added for each plugin separately
  costmap_converter/CostmapToLinesDBSRANSAC:
    cluster_max_distance: 0.4
    cluster_min_pts: 2
    ransac_inlier_distance: 0.15
    ransac_min_inliers: 10
    ransac_no_iterations: 2000
    ransac_remainig_outliers: 3
    ransac_convert_outlier_pts: True
    ransac_filter_remaining_outlier_pts: False
    convex_hull_min_pt_separation: 0.1

  costmap_converter/CostmapToPolygonsDBSMCCH:
    cluster_max_distance: 1.0
    cluster_min_pts: 5
    cluster_max_pts: 500
    convex_hull_min_pt_separation: 0.1