<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="wheel_radius" value="0.035"/>
<xacro:property name="wheel_width" value="0.015"/>
<xacro:property name="wheel_chassis_lenght_clearense" value ="0.022"/>
<xacro:property name="wheel_mass" value="1"/>
<xacro:property name="wheelbase_length" value="0.16"/>
<xacro:property name="wheel_chassis_offset" value="0.005"/>
<xacro:property name="parasite_wheel_radius" value="0.01"/>
<xacro:property name="parasite_wheel_width" value="0.01"/>
<xacro:property name="parasite_wheel_mass" value="1"/>
<xacro:property name="parasite_wheel_base_lenght_offset" value="0.01"/>
<xacro:property name="sx" value="0.001"/> 
<xacro:property name="sy" value="0.02"/> 
<xacro:property name="sz" value="0.018"/>
<xacro:property name="sensors_base_lenght_offset" value="0.025"/>
<xacro:property name="sensors_side_base_lenght_offset" value="0.02"/>
<xacro:property name="sensors_base_width_offset" value="-0.025"/>
<xacro:property name="chassis_length" value="0.18"/>
<xacro:property name="chassis_width" value="0.13"/>
<xacro:property name="chassis_height" value="0.039"/>
<xacro:property name="chassis_clearance" value="0.019"/>
<xacro:property name="chassis_mass" value="10"/>
<xacro:property name="lidar_to_base_height_clearence" value="0.021"/>
<xacro:property name="lidar_to_base_lenght_clearence" value="0.06"/>
<xacro:property name="lidar_radius" value="0.035"/>
<xacro:property name="lidar_height" value="0.035"/>
<xacro:property name="PI" value="3.1415926535897931"/>

<xacro:include filename="$(find my_description)/urdf/inertia.xacro"/> 
<xacro:include filename="$(find my_description)/urdf/macros.xacro"/> 
<xacro:include filename="$(find my_description)/urdf/materials.xacro"/> 

<link name = "world_link">
</link>

<joint name="world_to_base_link_joint" type="fixed">
    <parent link="world_link"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
</joint>

<link name="base_link">
    <visual>
        <origin xyz="0 0 ${chassis_clearance}" rpy="0 0 0"/>
        <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        <material name="blue"/>
    </visual>
    <collision>
        <origin xyz="0 0 ${chassis_clearance}" rpy = "0 0 0"/>
        <geometry>
            <box size = "${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
    </collision>

    <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
        <origin xyz="0 0 ${chassis_clearance}" rpy = "0 0 0"/>
    </xacro:inertial_box>
</link>

<xacro:wheel_macro parent_link="base_link" wheel_prefix="left" wheel_side="-1" width="${wheel_width}" radius="${wheel_radius}" mass="${wheel_mass}">
    <origin xyz= "${chassis_length/2 - wheel_chassis_lenght_clearense} ${chassis_width/2 + wheel_width/2 + wheel_chassis_offset} ${wheel_radius/2}"/>
    <!-- расположен посередине  расстояние от центра массы {/2 потому-что от центра}  {высота положения}-->
</xacro:wheel_macro>

<xacro:wheel_macro parent_link="base_link" wheel_prefix="right" wheel_side="1" width="${wheel_width}" radius="${wheel_radius}" mass="${wheel_mass}">
    <origin xyz= "${chassis_length/2 - wheel_chassis_lenght_clearense} ${-chassis_width/2 - wheel_width/2 - wheel_chassis_offset} ${wheel_radius/2}"/>
</xacro:wheel_macro>

<joint name = "parasite_wheel_joint" type="fixed">
    <parent link = "base_link"/>
    <child link = "parasite_wheel_link"/>
    <origin rpy="0 0 0" xyz="${-chassis_length/2 + parasite_wheel_base_lenght_offset} 0 ${-chassis_clearance/2}"/>
    <!-- <axis rpy="0 0 0" xyz="0 1 0"/> -->
</joint>

<link name = "parasite_wheel_link">
    <visual>
         <geometry>
            <cylinder length="${parasite_wheel_width}" radius="${parasite_wheel_radius}"/>
        </geometry>
        <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
    </visual>

    <collision>
        <geometry>
            <cylinder length="${parasite_wheel_width}" radius="${parasite_wheel_radius}"/>
        </geometry>
        <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
    </collision>

    <xacro:inertial_cylinder mass ="${parasite_wheel_mass}" length = "${parasite_wheel_width}" radius = "${parasite_wheel_radius}">
        <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
    </xacro:inertial_cylinder>
</link>

<joint name="base_to_lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin rpy="0 0 ${PI}" xyz="${chassis_length/2 -lidar_to_base_lenght_clearence} 0 ${chassis_height + lidar_to_base_height_clearence}"/>
    <!-- развернутый на 180 градусов  высота относительно base-->
</joint>

<link name = "lidar_link">
    <collision>
        <origin rpy="0 0 0" xyz="0 0 ${lidar_to_base_height_clearence}"/>
      <geometry>
        <cylinder length="${lidar_height}" radius="${lidar_radius}"/>
      </geometry>
    </collision>

    <visual>
        <geometry>
            <cylinder length="${lidar_height}" radius="${lidar_radius}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 ${lidar_to_base_height_clearence}"/>
    </visual>
</link>


<xacro:ir_sensor name="front_left" parent="base_link" sx="${sx}" sy="${sy}" sz="${sz}">
    <origin rpy="0 0 ${-(20)*PI/180}" xyz="${chassis_length/2 + sensors_side_base_lenght_offset} ${-chassis_width/2 - sensors_base_width_offset} 0.02"/>
</xacro:ir_sensor>

<xacro:ir_sensor name="front_center" parent="base_link" sx="${sx}" sy="${sy}" sz="${sz}">
    <origin rpy="0 0 0" xyz="${chassis_length/2 + sensors_base_lenght_offset} 0 0.02"/>
</xacro:ir_sensor>

<xacro:ir_sensor name="front_right" parent="base_link" sx="${sx}" sy="${sy}" sz="${sz}">
    <origin rpy="0 0 ${(20)*PI/180}" xyz="${chassis_length/2 + sensors_side_base_lenght_offset} ${chassis_width/2 + sensors_base_width_offset} 0.02"/>
</xacro:ir_sensor>

<xacro:ir_sensor name="back_left" parent="base_link" sx="${sx}" sy="${sy}" sz="${sz}">
    <origin rpy="0 0 ${-(160)*PI/180}" xyz="${-chassis_length/2 - sensors_side_base_lenght_offset} ${-chassis_width/2 - sensors_base_width_offset} 0.02"/>
</xacro:ir_sensor>

<xacro:ir_sensor name="back_center" parent="base_link" sx="${sx}" sy="${sy}" sz="${sz}">
    <origin rpy="0 0 0" xyz="${-chassis_length/2 - sensors_base_lenght_offset} 0 0.02"/>
</xacro:ir_sensor>

<xacro:ir_sensor name="back_right" parent="base_link" sx="${sx}" sy="${sy}" sz="${sz}">
    <origin rpy="0 0 ${(160)*PI/180}" xyz="${-chassis_length/2 - sensors_side_base_lenght_offset} ${chassis_width/2 + sensors_base_width_offset} 0.02"/>
</xacro:ir_sensor>

</robot>
